name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore --force --no-cache
    - name: Build
      run: dotnet build --configuration Release SentinelCloudinho.sln
    - name: Publish
      run: dotnet publish --configuration Release SentinelCloudinho.sln -o ./publish
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: sentinelcloudinho-kennedy  # Substitua pelo nome do seu App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
